--------------------------------------------
 CREATE TABLE UNPIVOT_TEST (
  ID              NUMBER,
  CUSTOMER_ID     NUMBER,
  PRODUCT_CODE_A  NUMBER,
  PRODUCT_CODE_B  NUMBER,
  PRODUCT_CODE_C  NUMBER,
  PRODUCT_CODE_D  NUMBER
);

INSERT INTO UNPIVOT_TEST VALUES (1, 101, 10, 20, 30, NULL);
INSERT INTO UNPIVOT_TEST VALUES (2, 102, 40, NULL, 50, NULL);
INSERT INTO UNPIVOT_TEST VALUES (3, 103, 60, 70, 80, 90);
INSERT INTO UNPIVOT_TEST VALUES (4, 104, 100, NULL, NULL, NULL);
COMMIT;

SELECT *FROM UNPIVOT_TEST;

SELECT *
FROM  UNPIVOT_TEST
UNPIVOT 
(
QUANTITY FOR PRODUCT_CODE IN (PRODUCT_CODE_A AS 'A', PRODUCT_CODE_B AS 'B', PRODUCT_CODE_C AS 'C', PRODUCT_CODE_D AS 'D')
);



--unpivot denemesi 
 SELECT *
 FROM DATA_ACCOUNT_PRODUCT_COPY
 UNPIVOT 
 (COLUMN_NAME FOR PRODUCT_INFOR IN ( SELECT PRODUCT_NAME
                                     FROM DATA_ACCOUNT_PRODUCT_COPY
                                     WHERE PRODUCT_NAME = 'product_1' or PRODUCT_NAME = 'product_2')
 );
 
 
 
 SELECT * FROM(--unpivot denemesi
 SELECT ACCOUNT_NO , TOPLAM, PRODUCT_NAME, YEAR_DATE
 FROM DATA_ACCOUNT_PRODUCT)
 UNPIVOT 
 (COLUMN_NAM FOR PRODUCT_INFOR IN (PRODUCT_NAME)
 );
 
 
