CREATE TABLE PRODUCT_INVOICE(--faturanin bilgisi
INVOICE_ID NUMBER CONSTRAINT INVOICE_ID_PROD_INVO_PK PRIMARY KEY,
ACCOUNT_NO NUMBER,
BILLED_AMT NUMBER,
BILLED_TAX NUMBER,
INVO_DATE_YEAR DATE);

ALTER TABLE PRODUCT_INVOICE
ADD CONSTRAINT ACCOUNT_NO_PRODINVO_UK UNIQUE (ACCOUNT_NO);