CREATE TABLE PRODUCT_INFORMATION( --urunun bilgisi
PRODUCT_ID NUMBER,
INVOICE_ID NUMBER, 
PRODUCT_NAME VARCHAR2(100)
);
ALTER TABLE PRODUCT_INFORMATION 
ADD CONSTRAINT PRODUCT_ID_PRODINFOR_PK PRIMARY KEY (PRODUCT_ID);

ALTER TABLE PRODUCT_INFORMATION 
ADD CONSTRAINT INVOICE_ID_PRODINFOR_PRODINVO_FK FOREIGN KEY(INVOICE_ID) REFERENCES PRODUCT_INVOICE(INVOICE_ID);

